### ISSUE TITLE
Google drive for faster rcnn features  and *hintscore.json is invalid 

### ISSUE THREAD

**Issue by alice-cool** [ItemZheng/KDDAug#2]
Download faster rcnn features
Download feature1.zip and feature2.zip from Google Drive, then unzip and merge them into data/rcnn_feature/.

**Comment by alice-cool** [comment]
Download extra data to train CSS (ID & OOD Teacher in KDDAug)
Download *hintscore.json files from [here](https://drive.google.com/drive/folders/1v0alq1zD4DuMCwlvBkikC96LuYIGbTq_), and move them to data folder.

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/210124778-2cbfb8d6-0a5c-42ef-8c75-374ddcc662fe.png)

**Comment by ItemZheng** [comment]
The repo [CSS-VQA](https://github.com/yanxinzju/CSS-VQA)  updated download url. And you can download here: https://mega.nz/folder/0JBzGBZD#YGgonKMnwqmeSZmoV7hjMg
