### ISSUE TITLE
CLIP-based Filtering 

### ISSUE THREAD

**Issue by ningkekeke** [ItemZheng/KDDAug#5]
First of all, thank you very much for the code and work you provided selflessly. When I executed the statement ‘python filter.py --ratio 0.1 --dataset v2’, the following error occurred. How can I solve it?
![image](https://github.com/ItemZheng/KDDAug/assets/61769804/15084456-9fcd-4079-974d-aa8fe39a7cd5)

**Comment by ItemZheng** [comment]
'image_path' is not necessary for running filter.py, you can just comment out these two lines of code. Or you can refer to `extract_clip_feature.py` LINE 53-75 to set up image path.
