### ISSUE TITLE
Don't understand the formula in the paper

### ISSUE THREAD

**Issue by mirial65** [ItemZheng/KDDAug#8]
Dear author,
In Section 3.3 of the paper: KD-based Answer Assignment，i can't understand that why is the numerator c_ood when calculating w_id?
<img width="510" alt="image" src="https://github.com/ItemZheng/KDDAug/assets/44187287/c4823e4a-629a-4d61-8a2c-4fe778eaf44e">

**Comment by ItemZheng** [comment]
c_id means the bias degree of ID Teacher. And our goal is to get an un-biased answer distribution. You can think of this equation as "w_id = 1 - c_id / (c_id + c_ood)".
